package geo

var COUNTRIES = map[string]string{
	"ad": "andorra",
	"ae": "united arab emirates",
	"af": "afghanistan",
	"ag": "antigua and barbuda",
	"ai": "anguilla",
	"al": "albania",
	"am": "armenia",
	"ao": "angola",
	"aq": "antarctica",
	"ar": "argentina",
	"as": "american samoa",
	"at": "austria",
	"au": "australia",
	"aw": "aruba",
	"ax": "aland islands",
	"az": "azerbaijan",
	"ba": "bosnia and herzegovina",
	"bb": "barbados",
	"bd": "bangladesh",
	"be": "belgium",
	"bf": "burkina faso",
	"bg": "bulgaria",
	"bh": "bahrain",
	"bi": "burundi",
	"bj": "benin",
	"bl": "saint-barthelemy",
	"bm": "bermuda",
	"bn": "brunei darussalam",
	"bo": "bolivia, plurinational state of",
	"bq": "bonaire, sint eustatius and saba",
	"br": "brazil",
	"bs": "bahamas",
	"bt": "bhutan",
	"bv": "bouvet island",
	"bw": "botswana",
	"by": "belarus",
	"bz": "belize",
	"ca": "canada",
	"cc": "cocos (keeling) islands",
	"cd": "congo, the democratic republic of the",
	"cf": "central african republic",
	"cg": "congo",
	"ch": "switzerland",
	"ci": "cote divoire",
	"ck": "cook islands",
	"cl": "chile",
	"cm": "cameroon",
	"cn": "china",
	"co": "colombia",
	"cr": "costa rica",
	"cu": "cuba",
	"cv": "cape verde",
	"cw": "curacao",
	"cx": "christmas island",
	"cy": "cyprus",
	"cz": "czech republic",
	"de": "germany",
	"dj": "djibouti",
	"dk": "denmark",
	"dm": "dominica",
	"do": "dominican republic",
	"dz": "algeria",
	"ec": "ecuador",
	"ee": "estonia",
	"eg": "egypt",
	"eh": "western sahara",
	"er": "eritrea",
	"es": "spain",
	"et": "ethiopia",
	"fi": "finland",
	"fj": "fiji",
	"fk": "falkland islands (malvinas)",
	"fm": "micronesia, federated states of",
	"fo": "faroe islands",
	"fr": "france",
	"ga": "gabon",
	"gb": "united kingdom",
	"gd": "grenada",
	"ge": "georgia",
	"gf": "french guiana",
	"gg": "guernsey",
	"gh": "ghana",
	"gi": "gibraltar",
	"gl": "greenland",
	"gm": "gambia",
	"gn": "guinea",
	"gp": "guadeloupe",
	"gq": "equatorial guinea",
	"gr": "greece",
	"gs": "south georgia and the south sandwich islands",
	"gt": "guatemala",
	"gu": "guam",
	"gw": "guinea-bissau",
	"gy": "guyana",
	"hk": "hong kong",
	"hm": "heard island and mcdonald islands",
	"hn": "honduras",
	"hr": "croatia",
	"ht": "haiti",
	"hu": "hungary",
	"id": "indonesia",
	"ie": "ireland",
	"il": "israel",
	"im": "isle of man",
	"in": "india",
	"io": "british indian ocean territory",
	"iq": "iraq",
	"ir": "iran, islamic republic of",
	"is": "iceland",
	"it": "italy",
	"je": "jersey",
	"jm": "jamaica",
	"jo": "jordan",
	"jp": "japan",
	"ke": "kenya",
	"kg": "kyrgyzstan",
	"kh": "cambodia",
	"ki": "kiribati",
	"km": "comoros",
	"kn": "saint kitts and nevis",
	"kp": "korea",
	"kr": "korea, republic of",
	"kw": "kuwait",
	"ky": "cayman islands",
	"kz": "kazakhstan",
	"la": "lao peoples democratic republic",
	"lb": "lebanon",
	"lc": "saint lucia",
	"li": "liechtenstein",
	"lk": "sri lanka",
	"lr": "liberia",
	"ls": "lesotho",
	"lt": "lithuania",
	"lu": "luxembourg",
	"lv": "latvia",
	"ly": "libya",
	"ma": "morocco",
	"mc": "monaco",
	"md": "moldova, republic of",
	"me": "montenegro",
	"mf": "saint martin (french part)",
	"mg": "madagascar",
	"mh": "marshall islands",
	"mk": "macedonia, the former yugoslav republic of",
	"ml": "mali",
	"mm": "myanmar",
	"mn": "mongolia",
	"mo": "macao",
	"mp": "northern mariana islands",
	"mq": "martinique",
	"mr": "mauritania",
	"ms": "montserrat",
	"mt": "malta",
	"mu": "mauritius",
	"mv": "maldives",
	"mw": "malawi",
	"mx": "mexico",
	"my": "malaysia",
	"mz": "mozambique",
	"na": "namibia",
	"nc": "new caledonia",
	"ne": "niger",
	"nf": "norfolk island",
	"ng": "nigeria",
	"ni": "nicaragua",
	"nl": "netherlands",
	"no": "norway",
	"np": "nepal",
	"nr": "nauru",
	"nu": "niue",
	"nz": "new zealand",
	"om": "oman",
	"pa": "panama",
	"pe": "peru",
	"pf": "french polynesia",
	"pg": "papua new guinea",
	"ph": "philippines",
	"pk": "pakistan",
	"pl": "poland",
	"pm": "saint pierre and miquelon",
	"pn": "pitcairn",
	"pr": "puerto rico",
	"ps": "palestine, state of",
	"pt": "portugal",
	"pw": "palau",
	"py": "paraguay",
	"qa": "qatar",
	"re": "reunion",
	"ro": "romania",
	"rs": "serbia",
	"ru": "russian federation",
	"rw": "rwanda",
	"sa": "saudi arabia",
	"sb": "solomon islands",
	"sc": "seychelles",
	"sd": "sudan",
	"se": "sweden",
	"sg": "singapore",
	"sh": "saint helena, ascension and tristan da cunha",
	"si": "slovenia",
	"sj": "svalbard and jan mayen",
	"sk": "slovakia",
	"sl": "sierra leone",
	"sm": "san marino",
	"sn": "senegal",
	"so": "somalia",
	"sr": "suriname",
	"ss": "south sudan",
	"st": "sao tome and principe",
	"sv": "el salvador",
	"sx": "sint maarten (dutch part)",
	"sy": "syrian arab republic",
	"sz": "swaziland",
	"tc": "turks and caicos islands",
	"td": "chad",
	"tf": "french southern territories",
	"tg": "togo",
	"th": "thailand",
	"tj": "tajikistan",
	"tk": "tokelau",
	"tl": "timor-leste",
	"tm": "turkmenistan",
	"tn": "tunisia",
	"to": "tonga",
	"tr": "turkey",
	"tt": "trinidad and tobago",
	"tv": "tuvalu",
	"tw": "taiwan, province of china",
	"tz": "tanzania, united republic of",
	"ua": "ukraine",
	"ug": "uganda",
	"um": "united states minor outlying islands",
	"us": "united states",
	"uy": "uruguay",
	"uz": "uzbekistan",
	"va": "holy see (vatican city state)",
	"vc": "saint vincent and the grenadines",
	"ve": "venezuela, bolivarian republic of",
	"vg": "virgin islands, british",
	"vi": "virgin islands, u.s.",
	"vn": "viet nam",
	"vu": "vanuatu",
	"wf": "wallis and futuna",
	"ws": "samoa",
	"ye": "yemen",
	"yt": "mayotte",
	"za": "south africa",
	"zm": "zambia",
	"zw": "zimbabwe",
}

var US_STATES = map[string]struct{}{
	"al": struct{}{},
	"ak": struct{}{},
	"az": struct{}{},
	"ar": struct{}{},
	"ca": struct{}{},
	"co": struct{}{},
	"ct": struct{}{},
	"de": struct{}{},
	"dc": struct{}{},
	"fl": struct{}{},
	"ga": struct{}{},
	"hi": struct{}{},
	"id": struct{}{},
	"il": struct{}{},
	"in": struct{}{},
	"ia": struct{}{},
	"ks": struct{}{},
	"ky": struct{}{},
	"la": struct{}{},
	"me": struct{}{},
	"md": struct{}{},
	"ma": struct{}{},
	"mi": struct{}{},
	"mn": struct{}{},
	"ms": struct{}{},
	"mo": struct{}{},
	"mt": struct{}{},
	"ne": struct{}{},
	"nv": struct{}{},
	"nh": struct{}{},
	"nj": struct{}{},
	"nm": struct{}{},
	"ny": struct{}{},
	"nc": struct{}{},
	"nd": struct{}{},
	"oh": struct{}{},
	"ok": struct{}{},
	"or": struct{}{},
	"pa": struct{}{},
	"ri": struct{}{},
	"sc": struct{}{},
	"sd": struct{}{},
	"tn": struct{}{},
	"tx": struct{}{},
	"ut": struct{}{},
	"vt": struct{}{},
	"va": struct{}{},
	"wa": struct{}{},
	"wv": struct{}{},
	"wi": struct{}{},
	"wy": struct{}{},
}

var CA_PROVINCES = map[string]struct{}{
	"ab": struct{}{},
	"bc": struct{}{},
	"mb": struct{}{},
	"nb": struct{}{},
	"nl": struct{}{},
	"ns": struct{}{},
	"nt": struct{}{},
	"nu": struct{}{},
	"on": struct{}{},
	"pe": struct{}{},
	"qc": struct{}{},
	"sk": struct{}{},
	"yt": struct{}{},
}
