package common

var CATEGORIES = map[string]struct{}{
	"arts and entertainment": struct{}{},
	"automotive":             struct{}{},
	"business":               struct{}{},
	"career":                 struct{}{},
	"family":                 struct{}{},
	"health":                 struct{}{},
	"food and drink":         struct{}{},
	"hobbies":                struct{}{},
	"home":                   struct{}{},
	"law and politics":       struct{}{},
	"news":                   struct{}{},
	"personal finance":       struct{}{},
	"dating and marriage":    struct{}{},
	"science":                struct{}{},
	"pets":                   struct{}{},
	"sports":                 struct{}{},
	"fashion":                struct{}{},
	"technology":             struct{}{},
	"travel":                 struct{}{},
	"real estate":            struct{}{},
	"shopping":               struct{}{},
	"spirituality":           struct{}{},
}
